classes:
  Knight:
    icon: IRON_SWORD
    abilities:
      sworddash: DIAMOND_SWORD
      easycrit: FEATHER
      stunblow: EYE_OF_ENDER
  Wizard:
    icon: STICK
    abilities:
  Archer:
    icon: BOW
    abilities:
  Citizen:
    icon: DIRT
players: