SpellLootChance: 20
classes:
  Knight:
    icon: IRON_SWORD
    abilities:
      sworddash: DIAMOND_SWORD
      easycrit: FEATHER
      stunblow: EYE_OF_ENDER
  Mage:
    icon: STICK
    spells:
      projectile: ARROW
      fireball: FIREWORK_CHARGE
      freeze: SNOWBALL
      poison: SKULL
      lightning: STICK
      retreat: NETHER_STAR
      invsteal: CHEST
  Archer:
    icon: BOW
  Citizen:
    icon: DIRT
BackpackRecipe:
  00: IRON_SWORD
  01: GOLD_BLOCK
  02: STICK
  10: IRON_BLOCK
  11: DIAMOND_BLOCK
  12: LAPIS_BLOCK
  20: BOW
  21: REDSTONE_BLOCK
  22: DIRT
SpellBackpackRecipe:
  00: LEATHER
  01: REDSTONE_BLOCK
  02: LEATHER
  10: REDSTONE_BLOCK
  11: CHEST
  12: REDSTONE_BLOCK
  20: LEATHER
  21: REDSTONE_BLOCK
  22: LEATHER
players: