name: RPGCore
version: ${project.version}
main: de.newdel.rpgcore.Main
api-version: 1.8
commands:
  reloadrpgcore:
    description: Reloads the config
    usage: /<command>
    permission: RPGCore.reload
  sworddash:
    description: Enables SwordDash
    usage: /<command>
  easycrit:
    description: Enables EasyCrit
    usage: /<command>
  stunblow:
    description: Enabled StunBlow
    usage: /<command>
  projectile:
    description: Equips projectile spell
    usage: /<command>
  fireball:
    description: Equips fireball spell
    usage: /<command>
  freeze:
    description: Equips freeze spell
    usage: /<command>
  poison:
    description: Equips poison spell
    usage: /<command>
  lightning:
    description: Equips lightning
    usage: /<command>
  retreat:
    description: Equips retreat spell
    usage: /<command>
  invsteal:
    description: Equips invsteal spell
    usage: /<command>
  arrowrain:
    description: Activates ArrowRain
    usage: /<command>
  class:
    description: Shows info about your class
    usage: /<command>
    permission: RPGCore.class
  switch:
    description: Switches your class
    usage: /<command>
    permission: RPGCore.switch
  aswitch:
    description: Switches a players class
    usage: /<command> [Player] [Class]
    permission: RPGCore.aswitch


permissions:
  RPGCore.*:
    description: Grants access to all RPGCore commands
    children:
      RPGCore.admin:
        description: Grants access to all RPGCore admin commands
        children:
          RPGCore.reload:
            description: Perm to reload the config
      RPGCore.user:
        description: Grants access to all RPGCore user commands
        children:
          RPGCore.use:
            description: Perm to use the RPG system
            default: true
          RPGCore.class:
            description: Perm to show info about your class
            default: true
          RPGCore.switch:
            description: Perm to switch your class
            default: true
          RPGCore.reset:
            description: Perm to reset your class
            default: true


