name: RPGCore
version: ${project.version}
main: de.newdel.rpgcore.Main
api-version: 1.8
commands:
  reloadrpgcore:
    description: Reloads the config
    usage: /<command>
    permission: RPGCore.reload
  sworddash:
    description: Enables SwordDash
    usage: /<command>
  easycrit:
    description: Enables EasyCrit
    usage: /<command>
  stunblow:
    description: Enabled StunBlow
    usage: /<command>
  projectile:
    description: Equips projectile spell
    usage: /<command>
  fireball:
    description: Equips fireball spell
    usage: /<command>
  freeze:
    description: Equips freeze spell
    usage: /<command>
  poison:
    description: Equips poison spell
    usage: /<command>
  lightning:
    description: Equips lightning
    usage: /<command>
  retreat:
    description: Equips retreat spell
    usage: /<command>
  invsteal:
    description: Equips invsteal spell
    usage: /<command>
  arrowrain:
    description: Activates ArrowRain
    usage: /<command>

permissions:
  RPGCore.*:
    description: Grants access to all RPGCore commands
    children:
      RPGCore.admin:
        description: Grants access to all RPGCore admin commands
        children:
          RPGCore.reload:
            description: Perm to reload the config
      RPGCore.user:
        description: Grants access to all RPGCore user commands
        children:


