name: RPGCore
version: ${project.version}
main: de.newdel.rpgcore.Main
api-version: 1.8
commands:
  reloadrpgcore:
    description: Reloads the config
    usage: /<command>
    permission: RPGCore.reload
  sworddash:
    description: Enables SwordDash
    usage: /<command>
  easycrit:
    description: Enables EasyCrit
    usage: /<command>
  stunblow:
    description: Enabled StunBlow
    usage: /<command>

permissions:
  RPGCore.*:
    description: Grants access to all RPGCore commands
    children:
      RPGCore.admin:
        description: Grants access to all RPGCore admin commands
        children:
          RPGCore.reload:
            description: Perm to reload the config
      RPGCore.user:
        description: Grants access to all RPGCore user commands
        children:


